### ISSUE TITLE
Tag name validation broken

### ISSUE THREAD

**Issue by chpio** [jaemk/migrant_lib#4]
Hi,

im trying to get a working sqlite migration setup for my app.

migrant lib version: 0.18.2

code:
```rust
        let config = Config::with_settings(&Settings::configure_sqlite()
            .database_path(&self.path)?
            .build()?);
        config.setup()?;
        let mut config = config.reload()?;
        config.use_migrations(&[
            EmbeddedMigration::with_tag("20180222095249_v1")?
                .up(include_str!("../migrations/20180222095249_v1/up.sql"))
                .down(include_str!("../migrations/20180222095249_v1/down.sql"))
                .boxed(),
        ])?;
        Migrator::with_config(&config)
            .direction(::migrant_lib::Direction::Up)
            .all(true)
            .apply()?;
        Ok(())
```
> Invalid tag `20180222095249_v1`. Tags can contain [a-z0-9-]

So i changed the tag to`20180222095249-v1` & deleted the sqlite file
1. run: all migrations pass
2. run:
  > Found a non-conforming tag in the database: `20180222095249-v1`. Generated tags must follow [0-9]{14}_[a-z0-9-]

It seem that it uses two validation methods, one for the tag used in the code (`[a-z0-9-]`) and another one for the tags coming from a sqlite db (`[0-9]{14}_[a-z0-9-]`).

**Comment by jaemk** [comment]
Yeah the dual validation formats is something I'm planning on either removing or making more explicit. The more strict timestamp format is the version required by the CLI tool so it can properly order migrations based on their name. The second version, which is intended for embedded migrations, is more relaxed since the order is explicitly defined in a slice. Currently to work around this you need to call `config.use_migrations` before any call to `config.reload` so the tag validation knows to use the less strict version [a-z0-9-]. This is breifly mentioned in the docs https://docs.rs/migrant_lib/0.18.2/migrant_lib/config/struct.Config.html#method.use_migrations, but it's not super clear and it's easy to miss.

Thanks for bringing this up!
